redis.uri=redis://localhost:6379
redis.key-prefix=vm

storage.s3.bucket=bucket
storage.s3.endpoint=http://localhost:9000
storage.s3.access-key=minio-root-user
storage.s3.secret-key=minio-root-password
