redis.uri=redis://localhost:6379
redis.key-prefix=vm

kafka.bootstrap.servers=localhost:9092
kafka.group.id=videomanager-extract-frame
kafka.topic.extract-frame.request=fe_sample_frame_request__norm
kafka.topic.extract-frame.done=fe_sample_frame_done__norm
kafka.auto-offset-reset=latest
kafka.poll.millis=1000

storage.s3.bucket=bucket
storage.s3.endpoint=http://localhost:9000
storage.s3.access-key=minio-root-user
storage.s3.secret-key=minio-root-password
