redis.uri=redis://localhost:6379
redis.key-prefix=vm

storage.s3.bucket=bucket
storage.s3.endpoint=http://localhost:9000
storage.s3.access-key=minio-root-user
storage.s3.secret-key=minio-root-password

kafka.bootstrap.servers=localhost:9092
kafka.group.id=videomanager-extract-frame
kafka.topic.extract-frame.request=fe_sample_frame_request__norm
kafka.topic.extract-frame.done=fe_sample_frame_done__norm
kafka.group.id.transcode=videomanager-transcode
kafka.topic.transcode.request=fe_transcode_request__norm
kafka.topic.transcode.done=fe_transcode_done__norm
kafka.auto-offset-reset=latest
kafka.poll.millis=1000

ffmpeg.bin=ffmpeg
ffmpeg.timeout.seconds=60
local.workspace.dir=.work

transcode.allowed-dimensions=1920x1080,1280x720,854x480,640x360
transcode.profiles.1920x1080=1280x720@2800k,854x480@1400k,640x360@800k
transcode.profiles.1280x720=854x480@1400k,640x360@800k,426x240@400k
transcode.profiles.854x480=640x360@800k,426x240@400k,256x144@200k
transcode.profiles.640x360=426x240@400k,256x144@200k,192x108@120k
